<div class="row">
    <div class="col-xs-12">
        <h1>TESTs</h1>
    </div>
    <div class="col-xs-12">
        <h2>FontAwesome test</h2>
        <ul class="fa-ul">
          <li><i class="fa-li fa fa-check-square"></i>List icons (like these)</li>
          <li><i class="fa-li fa fa-check-square"></i>can be used</li>
          <li><i class="fa-li fa fa-spinner fa-spin"></i>to replace</li>
          <li><i class="fa-li fa fa-square"></i>default bullets in lists</li>
        </ul>
    </div>
</div>
